version: "3"

x-debug-log: &debug
  DEBUG_LOG_LEVEL: 1
x-device-num: &device-num
  DEVICE_NUM: 3

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - proxynet

  pc:
    build:
      context: .
    container_name: pc
    environment:
      HOST: "pc"
      DEVICE_TYPE: "laboratory"
      <<: *debug
    networks:
      - proxynet

  server:
    build:
      context: .
    container_name: server
    environment:
      HOST: "server"
      DEVICE_TYPE: "wearable"
      <<: *device-num
      <<: *debug
    networks:
      - proxynet

  smartphones:
    build:
      context: .
    container_name: smartphones
    environment:
      HOST: "smartphone"
      DEVICE_TYPE: "wearable"
      <<: *device-num
      <<: *debug
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
